name = "Telescope"
uuid = "5cda3ad9-a1fd-4c59-8c0c-bd6100725b84"
authors = ["Joshua Higginbotham <jhigginbotham64@gmail.com> and contributors"]
version = "0.2.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Telescope_jll = "ae456e04-aaf2-55ce-80c6-09193969412e"

[compat]
Clang = "0.15"
CEnum = "0.4"
Telescope_jll = "0.2.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
